services:
  backend:
    build: ./backend
    ports:
      - "97:5000"
    volumes:
      - ./backend:/app
    environment:
      MONGO_URL: mongodb://mongo:27017/cmsdb
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
